### ISSUE TITLE
Fails to restore from mbox to group

### ISSUE THREAD

**Issue by bjarnek** [jay0lee/got-your-back#14]
I don't know if i'm doing something wrong or there is a bug. I grabbed a .mbox file from my gmail account (single label) and trying to upload it to a google group using GYB. 
However it fails. It worked fine with a backup taken by GYB but with .mbox files it doesnt. I need to see if i can get the mbox upload to work as i'm migrating a bunch of shared folders and converting them to .mbox and uploading to groups using GYB would be the best way (almost only way atm). 

this is what happens. 

```
Nurv:got-your-back-0.29 bmk$ python gyb.py --email test-indbakke-samarbejde@mydomain.com.test-google-a.com --action restore-group --action restore-mbox --local-folder "./input/coding.mbox" --use-admin admin@mydomain.com
Traceback (most recent call last):
  File "gyb.py", line 1323, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 575, in main
    imapconn = gimaplib.ImapConnect(generateXOAuthString(options.email, options.service_account), options.debug)
  File "/Users/bmk/Downloads/got-your-back-0.29/gimaplib.py", line 50, in ImapConnect
    imap_conn.authenticate('XOAUTH2', lambda x: xoauth_string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 351, in authenticate
    raise self.error(dat[-1])
imaplib.error: Lookup failed ru8mb72396831lbb
```

I have edited the above slightly in order to mask a bit of the details about domain ect. But both the admin user works, and the groups mail add is correct. And as said both work with a backup created by GYB but wha ti need is the ability to restore .mbox files into groups.

**Comment by muher** [comment]
Hi. I get the same error when trying to restore an mbox file from Ubuntu

Traceback (most recent call last):
  File "gyb.py", line 1323, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 601, in main
    sqlconn = sqlite3.connect(sqldbfile, detect_types=sqlite3.PARSE_DECLTYPES)
sqlite3.OperationalError: unable to open database file

Any suggestions?

**Comment by banchioa** [comment]
I also get the same error as muher trying to restore-mbox from Centos 6.2

Any help?

best regards,
adolfo

**Comment by cdolson** [comment]
I'm having the exact same problem on OS X. 

My arguments are: gyb --email c*****@gmail.com --action restore-mbox ~/Documents/ndgov\ mailbox/Inbox.mbox/

The error is: "Using backup folder GYB-GMail-Backup-c*****@gmail.com
Traceback (most recent call last):
  File "gyb.py", line 1323, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 601, in main
    sqlconn = sqlite3.connect(sqldbfile, detect_types=sqlite3.PARSE_DECLTYPES)
sqlite3.OperationalError: unable to open database file"

I think part of the problem might be the "Using backup folder" as I do not have that folder and this .mbox file was not made from a GYB backup. But, I'm not sure about that because I saw a message from Jay Lee on another board stating that it was possible to restore .mbox files in general: 

http://webapps.stackexchange.com/questions/71346/upload-emails-to-gmail-account-from-the-google-takeout-generated-mbox-file

**Comment by bjarnek** [comment]
Well we simply wound up not doing anything this way. We migrated from courier imap server to gmail using GAMME tool from google itself, and simply killed off groups and similar setups.
