### ISSUE TITLE
Getting an unauthorized_client error

### ISSUE THREAD

**Issue by ianwinsemius1** [jay0lee/got-your-back#159]
I've searched for anyone getting the same error, and haven't been able to find similar circumstances. 
GYB works great for all the backup and restore functions I use it for, but when I 

When I run:
 ./gyb --email test@domain.com --service-account --use-admin testadmin@domain.com --action restore-group --local-folder testgroup/ 
I receive the error "Error: unauthorized_client: Client is unauthorized to retrieve access tokens using this method."

The test@domain.com is a working g-suite group
The testadmin@domain.com is a superadmin, and the service account has had domain wide delegation activated, the scopes for the user are also enabled. 

The folder has a fresh backup of the email account in question, but not an mbox, its a folder/sqlite backup from gyb, I have also enabled the API for groups migration, as well as attempting to go to the https://console.developers.google.com/apis/api/groupsmigration.googleapis.com/overview?project="project#" location, but thats not actually the URI for my GYB project. 

Expected outcome :
Messages restored to the group test@domain.com group.

**Comment by ianwinsemius1** [comment]
RTFM. Sorry. I have resolved this issue on my own. Turns out you cannot use GAM oauth2service.json files for ALL of the functions of GYB.

**Comment by Obre** [comment]
I am not sure..I have the same error

Error: unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.

which client_id string needs to be parsed to the admin console?

the one with only numbers in it or the longer one with googleusercontent.com at the end?

**Comment by Obre** [comment]
works, it is the shorter one containing only numbers

**Comment by Obre** [comment]
works, it is the shorter one containing only numbers

**Comment by realdimas** [comment]
As mentioned in the API_SCOPE_MAPPING dict (https://github.com/jay0lee/got-your-back/blob/13c6d8438a4e44baba0c3d37a4450d1e8e8b0696/gyb.py#L1174-L1177), GYB requires these 4 OAuth scopes below:
1. https://mail.google.com/
1. https://www.googleapis.com/auth/apps.groups.migration
1. https://www.googleapis.com/auth/drive.appdata
1. https://www.googleapis.com/auth/userinfo.email

To re-use a GAM's Service Account file `oauth2service.json`, you would need to ensure that domain-wide delegation includes GYB-specific scopes above.

Additionally, since GAM attempts to refresh the Service Account key periodically, you should try to set a hard-link (and not copy) `oauth2service.json` file between GAM & GYB to make sure a refreshed key would be available to both CLI tools.
