### ISSUE TITLE
GYB tries to recreate existing nested mailbox label failing with 409 Conflict.

### ISSUE THREAD

**Issue by marcus905** [jay0lee/got-your-back#173]
Full steps to reproduce the issue:
1. Import a google takeout mbox file with labels on the same email address it was exported from
2. While importing it fails because of a label conflict

Expected outcome (what are you trying to do?):
Restore a google takeout file on the same mailbox with labels and all, without trying to recreate existing labels even if nested.

Actual outcome (what errors or bad behavior do you see instead?):
Errors out with

>> gyb.exe --email [redacted] --action restore-mbox --local-folder takeout --batch-size 100 --debug

[command runs...]

send: b'POST /gmail/v1/users/me/labels?fields=id&prettyPrint=true&alt=json HTTP/1.1\r\nHost: www.googleapis.com\r\naccept: application/json\r\naccept-encoding: gzip, deflate\r\nuser-agent: Got Your Back 1.01 | http://git.io/gyb | Jay Lee - jay0lee@gmail.com | Python 3.6.4 64-bit final | Windows-10-10.0.16299 AMD64 google-api-python-client/1.6.5 (gzip)\r\ncontent-type: application/json\r\ncontent-length: 107\r\nauthorization: [redacted]\r\n\r\n'
send: b'{"labelListVisibility": "labelShow", "messageListVisibility": "show", "name": "Mailing\\n Lists/LEDE/Devel"}'
reply: 'HTTP/1.1 409 Conflict\r\n'

409: Label name exists or conflicts - aborted
header: Vary header: Vary header: Content-Type header: Content-Encoding header: Date header: Expires header: Cache-Control header: X-Content-Type-Options header: X-Frame-Options header: X-XSS-Protection header: Server header: Alt-Svc header: Transfer-Encoding

**Comment by marcus905** [comment]
[log.txt](https://github.com/jay0lee/got-your-back/files/1957452/log.txt)

^^^

full log

**Comment by marcus905** [comment]
After further analysis, the error can possibly be disregarded as if the label exists it is actually unnecessary to create it anew. I'm looking for guidance on how to make GYB ignore these errors, but python is not my forte.

Any suggestion?

**Comment by Toon76** [comment]
I'm also facing this problem... couldn't restore my backup.
For me it occurs in the following scenario : 
- backup ok in a local folder 
- start to restore in another gmail account
- after a while I got a ConnectionResetError which killed gyb
- restarting the restore process causes the "409: Label name exists or conflicts - aborted" error

It looks like the labels created in the first run stays in cache during it but on the second run, from the momeny it's face a mail with a label created previously it goes wrong

Let me know if you find a way to ignore it !! I really need to restore all these mails :(

**Comment by KihOshk** [comment]
Hey all, 

I had this same issue with a ~12Gb one-file **.mbox** for a user that REALLY liked to label their Gmails.

This user used multi-level hierarchical label assignments, and the Takeout's resulting mbox file contained  `X-Gmail-Labels` comma-delimited, backslash-nested label name values which would sometimes contain unexpected newline characters preceding the spaces in multi-word labels.

To illustrate, one message header might have:

```
X-GM-THRID: 1606722029464184871
X-Gmail-Labels: Archived,Conferences/New York
Delivered-To: gyb@gmail.com
```

...while a following message might have (notice the CR between "New" and " York"):

```
X-GM-THRID: 1606722029464184899
X-Gmail-Labels: Archived,Conferences/New 
 York
Delivered-To: joe@gmail.com
```
Since GYB sees `New York` and `New\n York` as two unique labels, when GYB attempts to create the new "unique" `New\n York` via `callGAPI`, Google barfs and returns the 409-error as it must get scrubbed on their end before it tries to create another label. To overcome this, I scrubbed the labels as they're found in GYB by adding this band-aid in gyb.py [1279]:

```
          for label in labels:
            #FITZ-20180725 - scrub LF and CR from label
            label=label.replace('\n','').replace('\r','')
            #
            if label.lower() in reserved_labels:
```

-Fitz

**Comment by mcorner** [comment]
FWIW I ran into this 409 Conflict error using the version installed from the git.io bash script.  In downloaded master hoping to apply this fix from @KihOshk . I just ran the master version as is and didn't it went past the mail that was causing the conflict before.  So not sure, but try master first.
