### ISSUE TITLE
No more able to backup/fetch mails after restore

### ISSUE THREAD

**Issue by simon-el** [jay0lee/got-your-back#19]
I did initially a backup of my mails which worked fine:
python ./gyb.py  --email  xxx@gmail.com  --action backup --local-folder ./backup_local

To test the restore feature, I deleted 2 emails (from inbox and then from the trash) and then started the restore procedure:
python ./gyb.py  --email  xxx@gmail.com  --action restore --local-folder ./backup_local

This seemed to work - it took a while and showed some logs which indicated that all mails were uploaded (not only 2).

I did not really see, that the mails I deleted before were restored properly, as they did not appear in the all mail view.

When I try to fetch mail again with 
python ./gyb.py  --email  xxx@gmail.com  --action backup --local-folder ./backup_local
I get following error message:

```
Using backup folder ./backup_local
Using folder [Gmail]/All Mail
GYB needs to examine 124 messages
GYB already has a backup of 0 messages
GYB needs to backup 124 messages
Traceback (most recent call last):
  File "./gyb.py", line 1323, in <module>
    main(sys.argv[1:])
  File "./gyb.py", line 742, in main
    (message_num, label))
sqlite3.IntegrityError: UNIQUE constraint failed: labels.message_num, labels.label
```

If I retry to restore it looks as it would do nothing:
```
python ./gyb.py  --email   xxx@gmail.com  --action restore --local-folder ./backup_local

Using backup folder ./old/backup_simon
using IMAP folder [Gmail]/All Mail
```

**Comment by rsvargas** [comment]
Having the same problem here. 

Backed up an account and uploaded it to another account under a label. Now I can't backup the one I uploaded the emails to.

> gyb.exe --version
> Got Your Back 0.29
> Jay Lee - jay0lee
> Python 2.7.8 64-bit final
> Windows-8-6.2.9200 AMD64

>gyb.exe --service-account=xxx@developer.gserviceaccount.com --email=yyy@my.company

>Using backup folder GYB-GMail-Backup-yyy@my.company
Using folder [Gmail]/Todos os e-mails
GYB needs to examine 37136 messages
GYB already has a backup of 28800 messages
GYB needs to backup 8336 messages
> Traceback (most recent call last):
>   File "gyb.py", line 1323, in <module>
>   File "gyb.py", line 742, in main
> sqlite3.IntegrityError: columns message_num, label are not unique

**Comment by rsvargas** [comment]
Looks like the culprit are labels with quotes.

At lines gyb.py:683 and  gyb.py:795. The lexer `shlex.split` is called with the parameter `posix` as `False`, changing it to `True` allowed me to backup the email again. (A fresh new backup to not mess up the labels).

But there should be a reason to set the that parameter to `False` as the default value is `True`.
@jay0lee, is there a reason to this? Or this fix can be simply fixed by changing the parameter?
Also theres this pull request which also deals with labels with quotes: #25.

I believe that new backups can possibly be incompatible with the old ones due to changes in labels parsing...

You can of course change your labels so they don't contain any quotes, then you can safely back up your account.

**Comment by jay0lee** [comment]
IMAP versions are no longer supported. Please upgrade.
