### ISSUE TITLE
High memory usage during backup

### ISSUE THREAD

**Issue by alexandreblin** [jay0lee/got-your-back#193]
I confirm that:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/got-your-back/wiki

When running a backup task, the memory usage is really high. I'm running this command on a VM with 4GB of RAM. I would get a `MemoryError` on some accounts. I can increase the RAM of my VM but I fear that some big account could hit my memory limit again.

Full steps to reproduce the issue:
1. Run a backup task (this is my command: `gyb.py --email email@domain.com --local-folder backup/ --service-account --action backup`)
2. Watch memory usage

Expected outcome (what are you trying to do?):
Memory usage should not be huge

Actual outcome (what errors or bad behavior do you see instead?):
Memory usage can go up to 6GB.

![screenshot 2019-02-18 at 16 07 39](https://user-images.githubusercontent.com/1523191/52959754-56bfcf00-3397-11e9-8494-2118dddd5fdb.png)

I mitigated memory usage by using a lower `--batch-size` but it's still big.

**Comment by jay0lee** [comment]
Default batch size for backup is 100 messages. Each message in Gmail can be as large as 50mb in size:

https://support.google.com/a/answer/1366776?hl=en

so worst case scenario a batch of messages alonge can be about 5gb in size. Add to that metadata such as labels, state, memory copy operations, etc and this seems possible.

Generally this isn't a concern because most messages are no larger than 64kb in size but if you are backing up a very large mailbox with very large messages, you'll need to either lower batch size or run it on a machine with more physical memory. Not much else can be done here.
