### ISSUE TITLE
Unable to reauthorize gyb

### ISSUE THREAD

**Issue by delta-3** [jay0lee/got-your-back#199]
Please confirm the following:
* I have upgraded to the latest GYB release from https://github.com/jay0lee/got-your-back/releases and I still have this issue.

I am using GYB 1.21 for Windows

* I am typing the commands as described in the Releases page for GYB 1.20

Full steps to reproduce the issue:

I followed these steps:

  Fix Google authentication errors by allowing you to create your own Google project for GYB.
  if you still see errors after upgrading
    Run "gyb --action revoke --email you@domain.com" to revoke old authorization.
    Run "gyb --action create-project --email you@domain.com" to create your own project. 
      Follow all steps.
    Run "gyb --action quota --email you@domain.com" to reauthorize.

Expected outcome (what are you trying to do?): allow login to gmail to authorize gyb as a third-party app with account access.

Actual outcome (what errors or bad behavior do you see instead?): Gmail will not allow login and show this error message:
![download](https://user-images.githubusercontent.com/49175277/55381745-b3ef8a00-54d8-11e9-9e65-b39e28a2b454.jpg)

EDIT 12-APR-2019
Today I ran the command: gyb --action create-project --email you@domain.com
and the create project dialog started and successfully created the "Got Your Back Project". I then ran: gyb --action quota --email you@domain.com for each of the gmail accounts I want to backup and all were setup and gyb backups ran flawlessly. 

So I agree with shaffermonell NEVER MIND

**Comment by shaffermonell** [comment]
Same message here when attempting to use --action estimate on a new account.

**Comment by polisski** [comment]
Still no luck with public gmail (not G.Suite). 
with existing client_secrets.json : 
`--action revoke`   gives response that for this application (gyb) login with google account is temporarily blocked (because the application is not tested by Google yet)
When trying to create new project , GAM is authorized, but then:
`Authentication successful.
Creating project "Got Your Back Project"...
Checking project status...
{'name': 'operations/cp.8199331215320999943', 'metadata': {'@type': 'type.googleapis.com/google.cloudresourcemanager.v1.ProjectCreationStatus', 'ready': True}, 'done': True, 'error': {'code': 8, 'message': 'The project cannot be created because you have exceeded your allotted project quota.', 'details': [{'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'description': 'The project cannot be created because you have exceeded your allotted project quota.'}]}]}}`

**Comment by jay0lee** [comment]
That error indicates you have to many API projects, you need to go to
console.cloud.google.com and delete unused projects.

**Comment by polisski** [comment]
Me? I'm not a programmer, I didn't have any...

**Comment by polisski** [comment]
Opened cloud console... 10 gyb projects. How can I delete them?

**Comment by polisski** [comment]
> That error indicates you have to many API projects, you need to go to console.cloud.google.com and delete unused projects.

Found 10 projects gyb-project-bla-bla.. 
Marked all of them for deletion, they said projects will be deleted in a month.  
Still the same message with `--action create-project`

**Comment by bryantech** [comment]
Get this error restoring to anew gmail account.

https://raw.githubusercontent.com/jay0lee/got-your-back/master/project-apis.txt?
