### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by brettowe** [jay0lee/got-your-back#207]
The instructions in the wiki don't cover the current authorization requirements
An explanation why anything is needed in dev console to just backup email would be nice also.

**Comment by jay0lee** [comment]
PSA that the wiki is editable by anyone with a github account, care to contribute something? What exactly are you looking for?

**Comment by brettowe** [comment]
Editing is good but only useful when you know what needs to be added.
The directions covering setup for first time doing a backup aren't covered. I bumbled my way thought but I didn't take notes so redoing it would take almost as long

**Comment by jay0lee** [comment]
I can't offer much help if you can't offer much detail...

Can you clarify what you feel like is missing from:
https://github.com/jay0lee/got-your-back/wiki  ???

**Comment by boyeatssteak** [comment]
I'm not sure if this is the same concern that @brettowe had, but for me - I was confused about why a Google Cloud Services project needed to be created. [Step 3](https://github.com/jay0lee/got-your-back/wiki#step-3-running-gyb-for-the-first-time) indicates that the user needs to authorize GYB to "connect to your Google Account for Gmail data only", but my experience with v1.27 required granting GAM access to Google Cloud, and separately granting GYB access to Gmail.

While looking through other issues trying to figure this out, it seems like maybe somewhere along the line Google changed the requirements so that a Google Cloud Project is now required? Is that correct? Or is that only required for G-Suite customers (I'm just a regular @gmail).

I'd be happy to help revise the Wiki if I knew what the justification was for the Google Cloud Project requirement.

**Comment by owen-murphy** [comment]
Having just downloaded GYB (v. 1.34) and tried it for the first time, I can see that the wiki needs to be updated.
Step 3: Running GYB for the First Time
`gyb --email youremail@gmail.com --action estimate`

The app's console output will return:
```
ERROR: Please configure a project

To make GYB run you will need to populate the client_secrets.json file. 
```
The client_secrets.json file isn't mentioned on the wiki.  The error output includes the instruction to
```
Try running:

gyb --action create-project --email youremail@gmail.com
```
From eyeballing the gyb-setup script it seems to do the same thing, so perhaps that script should be mentioned on the wiki.

Running create-project failed for me, returning a 400 with the message the a precondition had failed, namely that "Google Cloud Platform service has been disabled.".  I signed up for a GCP account a few months ago, and the trial period has now expired, but it's not obvious to me why this might prevent backing up emails.  Since GCP isn't mentioned on the wiki, I'm at a loss of what to try next.  My email account is an original GSuite account.

I'm happy to update the wiki if I get past this and learn something that will help other new GYB users.

**Comment by lwcorp** [comment]
I've just fixed the documentation, so you might want to change the status to `fixed`.
