### ISSUE TITLE
[feature request] Add an argument to encrypt backups

### ISSUE THREAD

**Issue by RichyHBM** [jay0lee/got-your-back#238]
Hello, This request is in some part related to #230 and is a request to add an "--encrypt" argument that would let you encrypt emails on backup. Maybe saving the file as foobar.eml.enc? the argument would then require a "--decrypt" when restoring. Both of these could have a subargument that would be the password.

If not possible, is there any documentation on how GYB knows an email has been backed up locally? If I manyally encrypted the files and appended to the file, would GYB just back up all emails again?

**Comment by jay0lee** [comment]
leaving this open to track request and in case I ever find myself with tons of free time but this is unlikely to ever be implemented. The better choice would be to use an existing file / drive encryption solution that allows GYB to backup to a mounted encrypted drive / folder.

**Comment by paour** [comment]
It is really simple to use an off-the-shelf encrypted filesystem. I've used [GoCryptFS](https://github.com/rfjakob/gocryptfs) to do this, because it's a good match for GYB: it's reasonably fast, it doesn't add much overhead (some encrypted FS obfuscate the file size by adding padding), it's portable and easy to use (FUSE). I could add a section in the Wiki if you'd like @jay0lee.

**Comment by jay0lee** [comment]
I'm just going to go ahead and close this as "will never happen". There are very good per-platform (Windows/Linux/MacOS) tools for encrypting the underlying filesystem GYB is backing up to and I would suggest using those.
