### ISSUE TITLE
Support install via pip / PyPI

### ISSUE THREAD

**Issue by thatneat** [jay0lee/got-your-back#239]
This is a great package - why not support install via PyPI and pip?

Full steps to reproduce the issue:
1. `pip install got-your-back`

Expected outcome (what are you trying to do?):
Install got-your-back via Python's most common convenient install mechanism

Actual outcome (what errors or bad behavior do you see instead?):
The package is not on PyPI so it doesn't get installed!

**Comment by thatneat** [comment]
Is there a technical reason this would be hard? Seems like it would make adoption easier.

**Comment by AustinHay** [comment]
agreed on this. I spent a while circling to figure out why it wasn't working with `pip`. 

I tried installing manually via the mac installer you had, which surprisingly was complicated since in python3 you need to rename your packages as .py and its a double sub directory. 

(complaints aside, thank you so much for making this. I'm surprised google hasn't offered to buy this and incorporate it into their enterprise suite yet)

**Comment by LewisLebentz** [comment]
Interested in this too, would like to be able to use gyb with some automation.

**Comment by hudcap** [comment]
Hmm, I don't think this should be closed without some input from the author first...
