### ISSUE TITLE
Emails restored with an incorrect date

### ISSUE THREAD

**Issue by PhilipAtz** [jay0lee/got-your-back#266]
I am having this issue with the latest version of GYB, while using the commands as described in the wiki. I have backed up a large number of emails but, when restoring them to a different account, many of them appear with today's date. I am using one of them as an example to report this issue:

The mail headers in the original email contain:
> Date: 27 Jan 00 15:03:00
>   PDT
> 

This is backed up correctly in a file called:
> 2000\1\27\dcf5704246d276c.eml

When I check the _msg-db.sqlite_ database, I can see that this entry has a _message_internaldate_ of:
> 2000-01-27 22:03:00

However, when restored, the email appears in Gmail with today's date (25 April 2020). I check the headers of the restored email in the receiving Gmail account and I still see the correct date header:
> Date: 27 Jan 00 15:03:00
>   PDT

I also see the following appended to the email's headers at the top:
> Delivered-To: *********@gmail.com
> Received: by 2002:ab0:15e3:0:0:0:0:0 with SMTP id j32csp1383913uae;
>         Fri, 24 Apr 2020 18:00:15 -0700 (PDT)
> X-Google-Smtp-Source: APiQypLnTjUdlny4Raxnl4LAHIESBhPyOrfVF3cDjG6vzbNpzM/3VuRAVCO3tbxYhXaycfFksdrK5fgkbz9zKewSDw==
> X-Received: by 2002:a05:6102:737:: with SMTP id u23mr9179854vsg.211.1587776413897;
>         Fri, 24 Apr 2020 18:00:13 -0700 (PDT)
> Received: from 475950126779 named unknown by gmailapi.google.com with HTTPREST; Fri, 24 Apr 2020 18:00:13 -0700

While it is true that these emails had been originally imported into the originating Gmail account from another source (Thunderbird/Outlook), I do not see why they are restored with the wrong dates. The headers are read correctly by GYB and the _message_internaldate_ column is populated correctly, so I would expect the email to be received by Gmail correctly. Do you think maybe it would have worked if the date format was instead:
> Thu, 27 Jan 2000 15:03:00 -0700 (PDT)

If so, I can probably write a quick script that goes over the .eml files and transforms the dates:
**Update: It DOES work when I manually change the date in the .eml file!**

Could we have some functionality in GYB that checks the restored emails, compares them with the backup, and corrects their date if it is wrong? Perhaps in those cases we could have a command-line option to forcefully replace the _Date:_ header with a newly-serialised version of the date from _message_intermediatedate_ (which would be guaranteed to be parseable).

**Comment by PhilipAtz** [comment]
I have a hunch that this is a Y2K bug in all its glory. Not a bug in GYB but definitely a case when GYB can do more to fix things up.

**Comment by jay0lee** [comment]
Yes, the problem here is that your messages don't have a valid Date header format as you've found. When GYB calls the Gmail API to insert the messages, it tells Gmail to use the Date header as the internal date (which is what you see in message list view (internalDateSource=dateHeader):

https://developers.google.com/gmail/api/v1/reference/users/messages/import

this works well if the message is formatted correctly but when Gmail can't parse your messages with bad Date headers it falls back to the only other time it knows which is the current time the message was imported.

The challenge for GYB in terms of fixing this is:
1. GYB would need to modify your messages before restoring them which goes against GYB's goals of not making changes.
1. GYB would need to parse your invalid date header, figure out what date/time was meant by it and generate a valid date header. That can be very tricky without already knowing what's invalid about your date header.

So the short answer is the old computer saying: "garbage in, garbage out" :-) The quickest fix is probably for you to modify your existing messages headers and get correct date format on them.

**Comment by PhilipAtz** [comment]
Thank you for the quick response! Yes, I see the issue. Couldn't GYB pass the date from the _message_intermediatedate_ column instead of the one in the Date: header? (I mean without even trying to parse the Date: header at all)
