### ISSUE TITLE
G Suite - Need to explicitly add GYB to the whitelist first, before it can work

### ISSUE THREAD

**Issue by victorhooi** [jay0lee/got-your-back#279]
I hit this yesterday when trying to setup GYB on a new domain.

When trying to set the Gmail scopes, it failed (sorry, I should have captured full message)

But you need to add the GYB application (search by Client ID) to the whitelist for your domain.

This is found under Security, App access control, Manage Third-party App Access:

<img width="1866" alt="Screen Shot 2020-06-25 at 5 04 48 am" src="https://user-images.githubusercontent.com/243499/85616665-6fce4380-b6a1-11ea-9883-f8e574bf2479.png">
<img width="535" alt="Screen Shot 2020-06-24 at 2 38 24 pm" src="https://user-images.githubusercontent.com/243499/85616672-7361ca80-b6a1-11ea-8bf6-ccd0a4c4f652.png">
<img width="1902" alt="Screen Shot 2020-06-24 at 2 38 37 pm" src="https://user-images.githubusercontent.com/243499/85616709-7bba0580-b6a1-11ea-832f-e1ab2a22246e.png">

Does this need to be documented in the wiki?

**Comment by jay0lee** [comment]
You're getting this behavior because you've locked down which apps can access Gmail APIs and you don't trust your own domain's API projects. I don't believe those are default settings in G Suite but if you want to add a note about the error produced when attempting to use GYB with a untrusted project and how to resolve on the wiki that'd be fine.
