### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by mcdave1975** [jay0lee/got-your-back#284]
HI JayOlee,

I try gyb email davelodia@twoseasonsresorts.com

try to paste the link this the error.

Authorization Error
Error 400: admin_policy_enforced
Access to your account data is restricted by policies within your organization. Please contact the administrator for twoseasonsresorts.com for more information.
Request Details
access_type=offline
login_hint=davelodia@twoseasonsresorts.com
response_type=code
redirect_uri=urn:ietf:wg:oauth:2.0:oob
state=196qnO9qPmzVDYsSFm3C0hCSx8OoKQ
code_challenge_method=S256
hd=twoseasonsresorts.com
prompt=consent
client_id=683461650598
code_challenge=ZywNGYPbNjGeXjw4s-7EkPnrg9O0uL5bef2JCQO36s4
scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/apps.groups.migration https://www.googleapis.com/auth/drive.appdata openid

**Comment by bryantech** [comment]
Did you figure this out?

**Comment by klatys** [comment]
For anyone searching in future :)
[This](https://support.interviewplanner.com/hc/en-us/articles/360056363473-How-do-I-solve-Error-400-admin-policy-enforced-) worked for me, insted of client id in the guide use the one you see on the error page from google

**Comment by Par-to** [comment]
Can we wake this one up?

Part of the great google apps migration and an admitted noob.

I followed @klatys link above - substituting GAM for Interview Planner but still getting:

Authorization Error
Error 400: admin_policy_enforced
Access to your account data is restricted by policies within your organization. Please contact the administrator for xxxxx.co.nz for more information.
The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
If you’re the app developer, make sure that these request details comply with Google policies.

    access_type: offline
    login_hint: nick@xxxxx.co.nz
    response_type: code
    redirect_uri: urn:ietf:wg:oauth:2.0:oob
    state: jPTQDaVOdTX00KckoQSp6ZsJnrDYQO
    code_challenge_method: S256
    hd: xxxxx.co.nz
    prompt: consent
    client_id: 623641583239-snf24aeq4ul52be11mbem1c0ps6vnmad
    code_challenge: DtNnkQwCumeUcwrlibSF1YElK5pnn0c9IcYOTY_OpVc
    scope: https://www.googleapis.com/auth/userinfo.email https://mail.google.com/ https://www.googleapis.com/auth/apps.groups.migration https://www.googleapis.com/auth/drive.appdata openid

**Comment by cliffordp** [comment]
thank you @klatys and @marcodallagatta !
Because the articles could go down at any time, and neither was complete to address this specific issue, I'm documenting it directly in here:

Seeing this error? `Error 400: admin_policy_enforced`
<img width="497" alt="Image 2023-03-14 at 6 54 25 AM" src="https://user-images.githubusercontent.com/1812179/224993782-cfb95089-5e6c-42aa-8895-a79c7b79b40d.png">

Click the "error details" to get your "client_id"
<img width="489" alt="Image 2023-03-14 at 6 54 43 AM" src="https://user-images.githubusercontent.com/1812179/224993906-af059831-aa46-4773-809d-75a1997fd54b.png">

In Google Admin, go to [Security > API Controls > click "MANAGE THIRD-PARTY APP ACCESS"](https://admin.google.com/ac/owl)

Click "Add app" > "OAuth App Name Or Client ID"
<img width="475" alt="image" src="https://user-images.githubusercontent.com/1812179/224994623-d6c43a74-9fd3-4339-963e-85e0d1b7dcd7.png">

In the Search field, paste the "client_id" you copied earlier, then click "Search" button:
<img width="680" alt="image" src="https://user-images.githubusercontent.com/1812179/224994794-4c74f602-bd56-48a0-858b-661b00d916a6.png">

Give it the permissions you choose, such as "trusted/all"

===

That was all in the DESTINATION account when attempting to Restore. After I did that, I then got this error:  `Error 403: org_internal`
<img width="487" alt="Image 2023-03-14 at 7 33 48 AM" src="https://user-images.githubusercontent.com/1812179/225002623-61862651-e259-4e0a-91a1-a86210ec01bb.png">

So then I had to go back to the original/source/backup account's Google Cloud OAuth consent screen: `https://console.cloud.google.com/apis/credentials/consent?project=**gyb-project-...**`

Then click "MAKE EXTERNAL" then "Testing" in the popup
<img width="758" alt="image" src="https://user-images.githubusercontent.com/1812179/225001272-154e3cb9-10fc-4bd7-960e-53c061801df4.png">

Then add your DESTINATION account's email address as a Test User:
<img width="1475" alt="Image 2023-03-14 at 7 30 38 AM" src="https://user-images.githubusercontent.com/1812179/225002901-4037b6ce-d6f3-4a52-ba17-b1b6420cc5c7.png">

And then it worked 🥇
