### ISSUE TITLE
Memory Error when restoring MBOX

### ISSUE THREAD

**Issue by dfliess** [jay0lee/got-your-back#40]
![image](https://cloud.githubusercontent.com/assets/1449633/8144353/3d430da0-11b1-11e5-878d-54a579e0ff99.png)

It's a big mbox file (12GB aprox).

**Comment by jay0lee** [comment]
This would be very hard for GYB to solve because the Python 3 mbox libraries which GYB use read the full mbox file into memory when GYB asks for them to be opened.

My suggestion is to investigate tools that can split mbox files into smaller parts (say, no larger a file than 1/2 your systems memory).

There's some guidance at:
http://kb.mozillazine.org/Edit_large_mbox_files
for this.
