### ISSUE TITLE
<HttpError 400 when requesting https://www.goo gleapis.com/gmail/v1/users/me/messages/import?alt=json&neverMarkSpam=true&fields =id returned "Invalid From header">

### ISSUE THREAD

**Issue by jschafer72** [jay0lee/got-your-back#61]
I received this error after a couple hundred emails had already been restored.:

Using backup folder C:\Users\John\Documents\Johns_Gmail_Backup
restoring 10 messages (10/39719)
Traceback (most recent call last):
  File "<string>", line 1491, in <module>
  File "<string>", line 1112, in main
  File "C:\Users\jlee\Documents\GitHub\got-your-back\oauth2client\util.py", line
 137, in positional_wrapper
  File "C:\Users\jlee\Documents\GitHub\got-your-back\googleapiclient\http.py", l
ine 1378, in execute
  File "<string>", line 794, in restored_message
  File "C:\Users\jlee\Documents\GitHub\got-your-back\googleapiclient\http.py", l
ine 1372, in execute
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.goo
gleapis.com/gmail/v1/users/me/messages/import?alt=json&neverMarkSpam=true&fields
=id returned "Invalid From header">

**Comment by jschafer72** [comment]
Getting this error everytime i run gyb.  Any idea on why? Anyone?

**Comment by jay0lee** [comment]
This error implies the message you backed up has an invalid From header.
You can try adding:

--fast-restore

to your GYB command and those messages should succeed however messages
restored with fast restore are neither threaded into conversations nor
de-duplicated.

A future version of GYB will skip over these failures instead of erroring
out.

Jay

**Comment by jschafer72** [comment]
Thanks!

**Comment by fourjay** [comment]
I received this error as well. 

Looked for the erroring file which turns out to have had a hard wrap in the "From:" (as the error message indicated) i.e.:

From: "=?utf-8?Q?Augsburg=20Student=20Financial=20Services?=" <studentfinances
 @augsburg.edu>

The hard wrap appears to have come from the export process (also GYB). Is it possible that the Google API introduces the wrap? or the possibly the excessive long name is not account for on the file write?

**Comment by RolemanColeman** [comment]
I'm in the same boat with the 400 error.  Any idea when the future version will be released?

**Comment by JonathanCasey** [comment]
I ran into this as well, and in my case, my errors were due to invalid email addresses in the 'From' field.  These were messages that were created via an [SMS backup app](https://play.google.com/store/apps/details?id=com.zegoggles.smssync), and had put some messages with a from field in the form of 'myname' instead of 'myname@email.com'.  A few 'find' and 'sed' commands to adjust the malformed email addresses in my backup did the trick for me.

**Comment by maltokyo** [comment]
I get this error every time.  I dont want to particularly use fast-restore, as I would like the messages to remain threaded, and de-duped.
I wish I had the skill to contribute to the code, and fix this.

**Comment by JonathanCasey** [comment]
@maltokyo, are you able to identify which emails are causing the error?  If we can examine the emails, it is my experience that the problematic emails can be adjusted.  Personally, I dropped in a little code that caught this particular error and then spit out the problematic emails to a log file so I could review them individually afterwards and fix those specific ones.

**Comment by apendergrass** [comment]
I'm having this problem too and I don't know what email is causing it. Is there any easy way to make the skipping happen in this version of the code?

**Comment by jay0lee** [comment]
This is fixed in the latest GYB release.

**Comment by apendergrass** [comment]
Thanks @jay0lee! Update 0.43 is a win!
